title: Redsun
description: Red Sun - Apache Solr Search Integration for Redmine based on Sunspot
google_analytics: 
show_downloads: true
zip_url: https://github.com/dkd/redsun/archive/refs/heads/master.zip
tar_url: https://github.com/dkd/redsun/archive/refs/heads/master.tar.gz
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
